Main.js: ../../src/Graphics/Cocos2d/Cocos2d.hs ../../src/Graphics/Cocos2d/Cocos2d.js ../../javascript/cocos2d-haskell.js Main.hs ActionManagerTest.hs
	hastec Main.hs -i../../src/Graphics/Cocos2d --start=asap -XTypeSynonymInstances -XFlexibleInstances -XRankNTypes
