Main.js: ../../src/Graphics/Cocos2d.hs ../../src/Graphics/Cocos2d.js ../../src/Graphics/Cocos2d/TouchDelegate.hs ../../src/Graphics/Cocos2d/TouchDelegate.js ../../javascript/cocos2d-haskell.js Main.hs ActionManagerTest.hs
	hastec Main.hs -i../../src --start=asap -XTypeSynonymInstances -XFlexibleInstances -XRankNTypes
